version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: passwordroot
        MYSQL_DATABASE: tp
        MYSQL_USER: tpuser
        MYSQL_PASSWORD: passworduser
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=db
    restart: always
    ports:
        - 8070:80
    links:
        - db